version: '3.6'

services:
  telemetry-collector-server:
    container_name: oh_telemetry_collector_server_java
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '127.0.0.1:8013:8013'
    links:
      - 'postgres-service'
    depends_on:
      postgres-service:
        condition: service_healthy
    networks:
      - default
  postgres-service:
    container_name: postgres_service_java
    image: postgres:15.1
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ['CMD-SHELL', '/usr/bin/pg_isready -p 5433 -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10
    restart: on-failure
    command: -p 5433
    networks:
      - default
