version: '3.6'

services:
  postgres-service:
      container_name: postgres_service_bis
      image: postgres:14-alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres     
      restart:
        on-failure
      networks:
      - default
