version: '3.6'

services:
  postgres-service:
    container_name: postgres_service_bis
    image: postgres:latest
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: on-failure
    networks:
      - default
    command: -p 5433
